### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'pipelines/PPBS_train_pipeline_ScanNet_aa-pwm_atom-valency_frames-triplet_sidechain_Beff-500.data'

### ISSUE THREAD

**Issue by cardioAI** [jertubiana/ScanNet#3]
Traceback (most recent call last):
  File "I:/Kaidong/cardioAI/ScanNet-main/train.py", line 173, in <module>
    inputs,outputs,failed_samples = pipeline.build_processed_dataset(
  File "I:\Kaidong\cardioAI\ScanNet-main\preprocessing\pipelines.py", line 202, in build_processed_dataset
    io_utils.save_pickle(
  File "I:\Kaidong\cardioAI\ScanNet-main\utilities\io_utils.py", line 137, in save_pickle
    pickle.dump(env_, open(filename, 'wb'), protocol)
FileNotFoundError: [Errno 2] No such file or directory: 'pipelines/PPBS_train_pipeline_ScanNet_aa-pwm_atom-valency_frames-triplet_sidechain_Beff-500.data'

**Comment by jertubiana** [comment]
Hi, sorry for the delay. It looks like there is something wrong with your paths setup (I see both slash / and backslashes \?). Hope you solved it since then.
Best regards,
Jérôme
