### ISSUE TITLE
can not install successfully!

### ISSUE THREAD

**Issue by nongbaoting** [jertubiana/ScanNet#7]
```
-> % time python /dat1/apps/ScanNet/predict_bindingsites.py ./1yy9A.pdb  --noMSA --predictions_folder egfr_interface3
Using TensorFlow backend.
/dat1/nbt2/miniconda3/envs/py_scannet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/dat1/nbt2/miniconda3/envs/py_scannet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/dat1/nbt2/miniconda3/envs/py_scannet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/dat1/nbt2/miniconda3/envs/py_scannet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/dat1/nbt2/miniconda3/envs/py_scannet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/dat1/nbt2/miniconda3/envs/py_scannet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/dat1/nbt2/miniconda3/envs/py_scannet/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/dat1/nbt2/miniconda3/envs/py_scannet/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/dat1/nbt2/miniconda3/envs/py_scannet/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/dat1/nbt2/miniconda3/envs/py_scannet/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/dat1/nbt2/miniconda3/envs/py_scannet/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/dat1/nbt2/miniconda3/envs/py_scannet/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Predicting binding sites from pdb structures with ScanNet_interface_noMSA
i=2,file:1 not found
Traceback (most recent call last):
  File "/dat1/apps/ScanNet/predict_bindingsites.py", line 826, in <module>
    layer=layer
  File "/dat1/apps/ScanNet/predict_bindingsites.py", line 190, in predict_interface_residues
    del query_pdbs[i]


```

**Comment by jertubiana** [comment]
Hi Baoting,
Installation looks successful. However:
1/ It looks like the parser cannot find your pdb file. Have you checked the path?
2/ Have you created the repository egfr_interface3 before?

**Comment by nongbaoting** [comment]
Hi, jertubiana,
Thanks for your reply!
I have run successfully on another Linux-base machine with GPU, it seems ScanNet could not run on a machine without GPU!

**Comment by jertubiana** [comment]
Strange, since many people have managed to run it on CPU. Anyway, glad that you fixed your problem.Le 11 juil. 2023 à 9:25 AM, Baoting Nong ***@***.***> a écrit :﻿
Hi, jertubiana,
Thanks for your reply!
I have run successfully on another Linux-base machine with GPU, it seems ScanNet could not run on a machine without GPU!
